namespace: test
nameSuffix: -prod
resources:
- ../../bases/
- server/
- namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: minghsu0107/cicd-demo-ga
  newTag: main-ff7fa5a
